trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:  
  - job: Build
    displayName: 'Build Maven Project'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        java -version
      displayName: 'Install JDK 17'

    - script: |
        echo "Listing directory contents:"
        ls -R
      displayName: 'List directory contents'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'TourGuide/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'SampleSpringBootBuild'
        
        # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/ya
 
