# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- master

pool:
  vmImage: 'ubuntu-latest' 
  container: maven:3.8.1-openjdk-17-slim
  variables:
   - name: JAVA_HOME_11_X64
  value: '/usr/local/openjdk-17'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:  
  - job: Build
    displayName: 'Build Maven Project'
    steps:
    - script: |
        echo "Listing directory contents:"
        ls -R
      displayName: 'List directory contents'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: './TourGuide/pom.xml'  # Remove leading slash
        goals: 'clean package'  # Fix quotation marks
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'SampleSpringBootBuild'
