# Sync
trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "Setting up remotes"
    git remote remove azure 
    git remote add github https://github.com/pablo-alpes/TourGuideP8.git
    git remote add azure https://$(AZURE_DEVOPS_TOK)@dev.azure.com/pablo-miranda0404/_git/TourGuideP8

    echo "Fetching latest changes from GitHub"
    git fetch github --unshallow
    git fetch azure

    echo "Checking out branch $(Build.SourceBranchName)"
    git checkout $(Build.SourceBranchName)

    echo "Pushing changes to Azure DevOps"
    git push azure $(Build.SourceBranchName):refs/heads/$(Build.SourceBranchName) --force
  displayName: 'Sync GitHub branch with Azure DevOps'
