# pipe to keep update the branches
trigger:
  branches:
    include:
      - main    
      - develop 

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    git remote add github https://github.com/pablo-alpes/TourGuideP8.git
    git fetch github
    git push github $(Build.SourceBranchName)
  displayName: 'Sync Azure DevOps Repo with GitHub'
