version: '3.8'

services:
  tourguide:
    build:
      context: ./TourGuide
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - gps
      - rewards
      - pricer

  gps:
    image: openjdk:22-jdk-slim
    working_dir: /app
    volumes:
      - ./TourGuide/libs/gpsUtil.jar:/app/gpsUtil.jar
    command: ["java", "-jar", "/app/gpsUtil.jar"]
    ports:
      - "8081:8081"

  rewards:
    image: openjdk:22-jdk-slim
    working_dir: /app
    volumes:
      - ./TourGuide/libs/RewardCentral.jar:/app/RewardCentral.jar
    command: ["java", "-jar", "/app/RewardCentral.jar"]
    ports:
      - "8082:8082"

  pricer:
    image: openjdk:22-jdk-slim
    working_dir: /app
    volumes:
      - ./TourGuide/libs/TripPricer.jar:/app/TripPricer.jar
    command: ["java", "-jar", "/app/TripPricer.jar"]
    ports:
      - "8083:8083"
