services:
  tourguide:
    image: project8tourguide.azurecr.io/tourguide_tourguide:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - gps
      - rewards
      - pricer

  gps:
    image: project8tourguide.azurecr.io/tourguide_gps:latest
    ports:
      - "8081:8081"

  rewards:
    image: project8tourguide.azurecr.io/tourguide_rewards:latest
    ports:
      - "8082:8082"

  pricer:
    image: project8tourguide.azurecr.io/tourguide_pricer:latest
    ports:
      - "8083:8083"
